ArstegSolutions/Models/EmployeeSalary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArstegSolutions.Models
{
    public class EmployeeSalary
    {
        public decimal GrossSalary { get; set; }
        public decimal TaxDeductionAmount { get; set; }
        public decimal InHandSalary { get; set; }
    }
}

ArstegSolutions/Models/MyDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ArstegSolutions.Models
{
    public class MyDbContext : DbContext
    {
        public MyDbContext() : base("name=ArstegSolutionConStr") { }
        public DbSet<TaxSlab> TaxSlabs { get; set; }
    }
}

ArstegSolutions/Models/TaxSlab.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ArstegSolutions.Models
{
    public class TaxSlab
    {
        [Key]
        public int SlabId { get; set; }

        [Required]
        [DisplayName("Start Amount")]
        [DataType(DataType.Currency)]
        public decimal StartAmount { get; set; }

        [DisplayName("End Amount")]
        [DataType(DataType.Currency)]
        //        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal EndAmount { get; set; }

        [Required]
        public int Percentage { get; set; }
    }
}

ArstegSolutions/Controllers/CalculateNetSalaryController.cs
using ArstegSolutions.Models;
using System.Linq;
using System.Web.Mvc;

namespace ArstegSolutions.Controllers
{
    public class CalculateNetSalaryController : Controller
    {

        private MyDbContext db = new MyDbContext();
        // GET: CalculateNetSalary
        public ActionResult Index()
        {
            ViewData["TaxSlabs"] = db.TaxSlabs.ToList();
            if (TempData.ContainsKey("salary"))
            {
                var salary = TempData["salary"] as EmployeeSalary; TempData.Keep();
                return View(salary);
            }
            return View();

        }
        // POST: CalculateNetSalary/NetSalary
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NetSalary([Bind(Include = "GrossSalary")] EmployeeSalary salary)
        {
            if (ModelState.IsValid)
            {
                decimal taxableAmount = salary.GrossSalary;
                decimal taxValue = 0;
                foreach (var taxSlab in db.TaxSlabs.ToList().OrderBy(tax => tax.Percentage))
                {
                    if (taxSlab.Percentage <= 0) taxableAmount -= taxSlab.EndAmount;
                    else if (taxableAmount > 0)
                    {
                        var slabDiff = taxSlab.EndAmount - taxSlab.StartAmount;
                        if (taxableAmount > slabDiff)
                        {
                            taxValue += ((taxSlab.Percentage * slabDiff) / 100);
                            taxableAmount -= slabDiff;
                        }
                        else if (taxableAmount < slabDiff)
                        {
                            taxValue += ((taxSlab.Percentage * taxableAmount) / 100);
                            taxableAmount -= taxableAmount;
                        }
                    }
                    salary.TaxDeductionAmount = taxValue;
                    salary.InHandSalary = salary.GrossSalary - taxValue;
                }
            }
            TempData["salary"] = salary;
            return RedirectToAction("Index");
        }
    }
}

ArstegSolutions/Controllers/HomeController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ArstegSolutions.Models;

namespace ArstegSolutions.Controllers
{
    public class HomeController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Home
        public ActionResult Index()
        {
            return View(db.TaxSlabs.ToList());
        }

        // GET: Home/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaxSlab taxSlab = db.TaxSlabs.Find(id);
            if (taxSlab == null)
            {
                return HttpNotFound();
            }
            return View(taxSlab);
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SlabId,StartAmount,EndAmount,Percentage")] TaxSlab taxSlab)
        {
            if (ModelState.IsValid)
            {
                db.TaxSlabs.Add(taxSlab);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taxSlab);
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaxSlab taxSlab = db.TaxSlabs.Find(id);
            if (taxSlab == null)
            {
                return HttpNotFound();
            }
            return View(taxSlab);
        }

        // POST: Home/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SlabId,StartAmount,EndAmount,Percentage")] TaxSlab taxSlab)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taxSlab).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taxSlab);
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaxSlab taxSlab = db.TaxSlabs.Find(id);
            if (taxSlab == null)
            {
                return HttpNotFound();
            }
            return View(taxSlab);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaxSlab taxSlab = db.TaxSlabs.Find(id);
            db.TaxSlabs.Remove(taxSlab);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArstegSolutions/Views/CalculateNetSalary/Index.cshtml
@model ArstegSolutions.Models.EmployeeSalary

@{var tasSlabs = @ViewBag.TaxSlabs;
}
<br />

<table class="table">
    <tr>
        <th>
            Min Amount
        </th>
        <th>
            Max Amount
        </th>
        <th>
            Percentage
        </th>
    </tr>
    @foreach (var item in ViewData["TaxSlabs"] as IList<ArstegSolutions.Models.TaxSlab>)
    {
        <tr>
            <td>
                @item.StartAmount
            </td>
            <td>
                @item.EndAmount
            </td>
            <td>
                @item.Percentage
            </td>
        </tr>
    }
</table>


@*@using (Html.BeginForm("NetSalary", "CalculateNetSalary", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.GrossSalary)
            <div class="form-group">
                @Html.LabelFor(model => model.GrossSalary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GrossSalary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GrossSalary, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Calculate" class="btn btn-default" />
                </div>
            </div>
        </div>
    }*@



<div class="well">
    <div class="form-horizontal">
        <form action="/CalculateNetSalary/NetSalary" method="post">
            @Html.AntiForgeryToken()

            <div class="row">
                <div class=" col-md-2">
                    <div class="control-label pull-left "><b>Gross Salary</b>  </div>
                    <input type="text" name="GrossSalary" class="form-control" />    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</div>

@if (Model != null && Model.GrossSalary > 0)
{
    <table class="table">
        <tr>
            <th><b>GrossSalary</b></th>
            <td>@Model.GrossSalary</td>
        </tr>
        <tr>
            <th><b>TaxDeductionAmount</b></th>
            <td>@Model.TaxDeductionAmount</td>
        </tr>
        <tr>
            <th><b>InHandSalary</b></th>
            <td>@Model.InHandSalary</td>
        </tr>
    </table>
}

ArstegSolutions/Views/Home/Create.cshtml
@model ArstegSolutions.Models.TaxSlab

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaxSlab</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Percentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Percentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ArstegSolutions/Views/Home/Delete.cshtml
@model ArstegSolutions.Models.TaxSlab

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaxSlab</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Percentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Percentage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ArstegSolutions/Views/Home/Details.cshtml
@model ArstegSolutions.Models.TaxSlab

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaxSlab</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Percentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Percentage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SlabId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ArstegSolutions/Views/Home/Edit.cshtml
@model ArstegSolutions.Models.TaxSlab

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaxSlab</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SlabId)

        <div class="form-group">
            @Html.LabelFor(model => model.StartAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Percentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Percentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ArstegSolutions/Views/Home/Index.cshtml
@model IEnumerable<ArstegSolutions.Models.TaxSlab>

@{
    ViewBag.Title = "Index";
}

<h2>Salary Slab List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Percentage)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Percentage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.SlabId }) |
                @Html.ActionLink("Details", "Details", new { id = item.SlabId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.SlabId })
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Calculate Net Salary", "Index", "CalculateNetSalary", new { area = "" }, new { @class = "btn btn-success" })

ArstegSolutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ARSTEG SOLUTIONS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse pull-right">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Calculate Net Salary", "Index", "CalculateNetSalary", new { area = "" }, new { @class = "navbar-brand" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <br /><br /><br />   <hr />
        <footer class="bottom">
            <p>&copy; @DateTime.Now.Year - ARSTEG SOLUTIONS, Machine Test from Ankit Sahay - Mob :  +91-9415-151212 || e-mail : ankitsahay1990@@gmail.com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>